export const general = {
    main: {
        height: 'auto',
        borderRadius: 20,
        display: 'flex',
        marginTop: 'auto',
        marginBottom: 'auto',
        marginLeft: 'auto',
        marginRight: 'auto',
        alignItems: 'center',
        overflow: 'hidden',
        position: 'relative',
    },
    locale: {
        height: '100%',
        width: '100%',
        fontFamily: 'rubikBoldItalic',
        color: '#034d06',
        flexBasis: '100%',
        borderRadius: 12,
        backgroundColor: 'rgba(245, 245, 245, 1)',
        display: 'flex',
        marginHorizontal: 'auto',
        textTransform: 'uppercase',
        textAlign: 'center',
        justifyContent: 'center',
        zIndex: 10,
    },
    button: {
        marginVertical: 10,
        marginHorizontal: 'auto',
        justifyContent: 'center',
        backgroundColor: '#2f98ed',
        borderWidth: 2,
        borderColor: '#d1ae52',
        borderRadius: 10,
    },
    buttonText: {
        position: 'relative',
        fontFamily: 'rubikSemiBold',
        textAlign: 'center',
        textShadowRadius: 3,
        color: '#ffcea1',
        textShadowColor: '#000',
        letterSpacing: 1,
        paddingTop: 3,
    },
};
